var lang = {
    loading: 'Carregando...',
    search: 'Buscar endereÃ§o',
    searching: 'Buscando...',
    summary_total: 'Total',
    summary_shipping: 'Frete',
    out_of_stock: "Esgotado.",
    out_of_stock_long: "Esta opÃ§Ã£o estÃ¡ esgotada, por favor selecione outra.",
    all_not_available: "IndisponÃ­vel.",
    all_not_available_long: "Este produto estÃ¡ indisponÃ­vel.",
    not_available: "IndisponÃ­vel.",
    not_available_long: "Esta opÃ§Ã£o estÃ¡ indisponÃ­vel, por favor selecione outra.",
    choose_option: "Escolha uma opÃ§Ã£o.",
    choose_option_long: "Por favor, selecione todas as opÃ§Ãµes do produto para continuar a compra.",
    radio_not_selected: "Por favor, selecione uma opÃ§Ã£o no campo ",
    field_not_filled: "Por favor, preencha o campo ",
    need_variant: "Por favor, selecione as opÃ§Ãµes dos produtos",
    email: "E-mail",
    firstname: "Nome",
    lastname: "Sobrenome",
    birthday: "Data de nascimento",
    sex: "Sexo",
    cpf: "CPF",
    phone: "Telefone",
    zip: "CEP",
    zone_id: "Estado",
    city: "Cidade",
    district: "Bairro",
    address1: "EndereÃ§o",
    anumber: "NÃºmero",
    module: "Forma de pagamento",
    shipping_method: "Forma de entrega",
    password: "Senha",
    confirm: "Confirmar Senha",
    submit_order: "Finalizar compra",
    insert_address_first: "Por favor informe seu CEP primeiro.",
    calculating_shipping: "Calculando o frete"
};
